title:             Heilan Cyber
description:       ...in the pursuit of knowledge
author:            HC
#url:               "localhost:4000"
url:               "https://heilancoos.github.io"
baseurl:            ""
# Social Profiles
github_username:   heilancoos
linkedin_username: alexis-o
twitter_username: '_heilancoos'
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

